version: "3"

services:
  cfg-service:
    build: .
    hostname: cfg-service
    container_name: cfg-service
    restart: always
    environment:
      ZKHOSTS: ${CFGSERVICE_ZKHOSTS}
      ZKTIMEOUT: ${CFGSERVICE_ZKTIMEOUT}
      RESTPORT: ${CFGSERVICE_RESTPORT}
    ports:
      - 8878:${CFGSERVICE_RESTPORT}
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2184:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  zookeeper-ui:
    image: elkozmon/zoonavigator:latest
    restart: always
    hostname: zookeeper-ui
    container_name: zookeeper-ui
    ports:
      - 9898:9000
    environment:
      - HTTP_PORT=9000
    depends_on:
      - zoo1
      - zoo2
      - zoo3
  